export const presentes = [
    { id: 1, imagem: "https://tse3.mm.bing.net/th?id=OIP.cOXTQq7ugvT7TjV8ehMyjAHaHa&pid=Api", nome: "Jogo de Lençóis", categoria: "Cama", preço: 120.00, ativo: true },
    { id: 2, imagem: "https://tse1.mm.bing.net/th?id=OIP.z5eYpZXdQWS-vhjmBZubWgHaDl&pid=Api", nome: "Toalhas de Banho", categoria: "Banho", preço: 80.00, ativo: true },
    { id: 3, imagem: "https://tse4.mm.bing.net/th?id=OIP.Nr7QVrFHx_QgbmyAi2VtGwHaHa&pid=Api", nome: "Conjunto de Panelas", categoria: "Cozinha", preço: 250.00, ativo: true },
    { id: 4, imagem: "https://tse1.mm.bing.net/th?id=OIP.vpuvkoZrCy7sTLLf6FD-ygHaHa&pid=Api", nome: "Jogo de Talheres", categoria: "Cozinha", preço: 100.00, ativo: true },
    { id: 5, imagem: "https://tse3.mm.bing.net/th?id=OIP.IOyUUimc7zIZeQo1T4M1YgHaHa&pid=Api", nome: "Conjunto de Pratos", categoria: "Cozinha", preço: 150.00, ativo: true },
    { id: 6, imagem: "https://tse4.mm.bing.net/th?id=OIP.tmuHcbvB9vzplTYlxHJdgwHaHa&pid=Api", nome: "Copos de Vidro", categoria: "Cozinha", preço: 60.00, ativo: true },
    { id: 7, imagem: "https://tse4.mm.bing.net/th?id=OIP.fUeBTHfv1I1ekhAjhbb2FwHaHa&pid=Api", nome: "Panela de Pressão", categoria: "Cozinha", preço: 130.00, ativo: true },
    { id: 8, imagem: "https://tse2.mm.bing.net/th?id=OIP.iNmPJmpUIYVmrEMgJi9X4QHaHa&pid=Api", nome: "Frigideira Antiaderente", categoria: "Cozinha", preço: 90.00, ativo: true },
    { id: 9, imagem: "https://tse3.mm.bing.net/th?id=OIP.UejSOwiChTiz-4txNWIl4gHaHa&pid=Api", nome: "Liquidificador", categoria: "Eletrodomésticos", preço: 200.00, ativo: true },
    { id: 10, imagem: "https://tse3.mm.bing.net/th?id=OIP.SCX49rLakpoBYpQLtkhNLgHaHa&pid=Api", nome: "Ferro de Passar", categoria: "Eletrodomésticos", preço: 150.00, ativo: true },
    { id: 11, imagem: "https://tse2.mm.bing.net/th?id=OIP.7DZLauAVKWj7ynMQvvujaQHaHa&pid=Api", nome: "Tábua de Passar", categoria: "Casa", preço: 80.00, ativo: true },
    { id: 12, imagem: "https://tse2.mm.bing.net/th?id=OIP.-eIfo1Paz_TNy3tap9B2GwHaHa&pid=Api", nome: "Cortinas", categoria: "Casa", preço: 180.00, ativo: true },
    { id: 13, imagem: "https://tse1.mm.bing.net/th?id=OIP.RXRQWQJtWZsoDFUxq9ytegHaJQ&pid=Api", nome: "Roupas de Mesa", categoria: "Cozinha", preço: 90.00, ativo: true },
    { id: 14, imagem: "https://http2.mlstatic.com/D_Q_NP_2X_998675-MLB72098223701_102023-T.webp", nome: "Travesseiros", categoria: "Cama", preço: 100.00, ativo: true },
    { id: 15, imagem: "https://tse4.mm.bing.net/th?id=OIP.PUC9uU5Oqyr-rxD578ZltgHaHa&pid=Api", nome: "Edredom", categoria: "Cama", preço: 200.00, ativo: true },
    { id: 16, imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHSR_jt_vCqf-BLzS_PiFXqmlYnWxYF-CzIQ&s", nome: "Colcha", categoria: "Cama", preço: 150.00, ativo: true },
    { id: 17, imagem: "https://tse3.mm.bing.net/th?id=OIP.N2Fhhn60WAMBwFIk29fcAgHaHa&pid=Api", nome: "Jogo de Tapetes", categoria: "Casa", preço: 200.00, ativo: true },
    { id: 18, imagem: "https://tse2.mm.bing.net/th?id=OIP.Usw3yWFuaHaSMr_11o_e5AHaHa&pid=Api", nome: "Escorredor de Louças", categoria: "Cozinha", preço: 60.00, ativo: true },
    { id: 19, imagem: "https://tse2.mm.bing.net/th?id=OIP.XDYSJBsmXS3eiNQ1tO52RQHaHa&pid=Api", nome: "Porta-Condimentos", categoria: "Cozinha", preço: 80.00, ativo: true },
    { id: 20, imagem: "https://tse2.mm.bing.net/th?id=OIP.3m3IZ8d5HyOR6SqIOpZLrgHaJ4&pid=Api", nome: "Panos de Prato", categoria: "Cozinha", preço: 40.00, ativo: true },
    { id: 21, imagem: "https://tse3.mm.bing.net/th?id=OIP.cqD_z6cBF5bDhbsthibv8AHaHa&pid=Api", nome: "Lixeira", categoria: "Casa", preço: 50.00, ativo: true },
    { id: 22, imagem: "https://tse1.mm.bing.net/th?id=OIP.MOusnhl5UfHMy5L3_cAECwHaHa&pid=Api", nome: "Espremedor de Frutas", categoria: "Cozinha", preço: 100.00, ativo: true },
    { id: 23, imagem: "https://tse4.mm.bing.net/th?id=OIP.UPvh4RUr_pseYUKxDmAwwQHaHa&pid=Api", nome: "Balde de Limpeza", categoria: "Casa", preço: 60.00, ativo: true },
    { id: 24, imagem: "https://tse1.mm.bing.net/th?id=OIP.tNqWz1aHNTUxokz3s7ZATQHaHa&pid=Api", nome: "Vassouras", categoria: "Casa", preço: 30.00, ativo: true },
    { id: 25, imagem: "https://cdn.awsli.com.br/2500x2500/996/996743/produto/264954995/rodos-ebamm57zv4.png", nome: "Rodos", categoria: "Casa", preço: 25.00, ativo: true },
    { id: 26, imagem: "https://tse1.mm.bing.net/th?id=OIP.dQEe2uelITFIwODrR_nuVwHaG0&pid=Api", nome: "Escovas de Limpeza", categoria: "Casa", preço: 40.00, ativo: true },
    { id: 27, imagem: "https://tse1.mm.bing.net/th?id=OIP.jxu_VGPrQWsL90V5g8Ez4QHaGq&pid=Api", nome: "Bandejas para Servir", categoria: "Cozinha", preço: 120.00, ativo: true }
];
